/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car.glb --transform 
Files: public/models/car.glb [19.03MB] > /home/ry/Pictures/TechCognify/Al-Khaliq-Tracker-Company-PVT/Al-Khaliq-Tracker-Company-PVT/car-transformed.glb [1.99MB] (90%)
Author: Maroi Mister Let Me Think Official 3D Studio (https://sketchfab.com/homicivan53)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2022-acura-nsx-type-s-3d3d1449aba7481788515d31df448bea
Title: 2022 Acura NSX Type S
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_9.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022BadgeA_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial001} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Carbon1_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial002} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022EngineA_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille1A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille2A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille3A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille4A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille5A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille6A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille7A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022Grille8A_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022InteriorTillingA_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022InteriorA_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022LightEmissiveA_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022LightA_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022ManufacturerPlateA_Material} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.PaletteMaterial003} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.PaletteMaterial004} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.PaletteMaterial005} position={[0, 0.001, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.PaletteMaterial006} scale={0.01} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022_Wheel1B_3D_3DWheel1B_Material} position={[0.008, 0.003, 0.013]} rotation={[0, 0, 0.017]} scale={0.01} />
      <mesh geometry={nodes.Object_2207.geometry} material={materials.Acura_NSXTypeSRewardRecycled_2022_CallipersCalliperA_Zone_Material1} position={[0.008, 0.003, 0.013]} rotation={[0, 0, 0.017]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
